### ISSUE TITLE
http://13.124.127.226:3000/boardView?boardId=nn 미생성 게시물 접근 가능

### ISSUE THREAD

**Issue by luckjjh** [1004mapa2/lolProject#40]
nn에 아직 생성 안 된 게시글 번호 입력 해 접근 후 댓글 or 좋아요 기능 사용시 게시물 생성 전에 미리 적용 됨
![image](https://github.com/1004mapa2/lolProject/assets/68142773/322b19e3-411d-4f53-bace-2cb6b19150d5)
댓글 작성 시간 15:16, 게시글 작성시간 15:17

**Comment by 1004mapa2** [comment]
해결
